# Generated by Django 3.2.6 on 2021-10-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
